/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 computer1.gltf 
Author: Lelouch (https://sketchfab.com/severljs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nec-computer-e3f85ee8ee2340cb9165148353f49d12
Title: NEC computer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/computer/computer1.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Cube_low_Base_0.geometry} material={materials.Base} position={[0.332, 31.83, 1.429]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube001_low_Glass_0.geometry} material={materials.Glass} position={[49.062, 40.908, 11.49]} rotation={[-Math.PI / 2, 0.022, 0]} scale={100} />
          <mesh geometry={nodes.Cube028_low_Parts_0.geometry} material={materials.Parts} position={[50.031, 40.313, -25.315]} rotation={[-Math.PI / 2, 1.352, 0]} scale={100} />
          <mesh geometry={nodes.Cube029_low_Parts_0.geometry} material={materials.Parts} position={[50.031, 40.313, -39.869]} rotation={[-Math.PI / 2, 1.352, 0]} scale={100} />
          <mesh geometry={nodes.Cube030_low_Parts_0.geometry} material={materials.Parts} position={[42.732, 6.311, 28.68]} rotation={[0, 1.414, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder_low_Parts_0.geometry} material={materials.Parts} position={[45.145, 8.999, -29.217]} rotation={[-1.412, 1.412, -0.126]} scale={100} />
          <mesh geometry={nodes.Cylinder002_low_Parts_0.geometry} material={materials.Parts} position={[45.145, 8.999, -39.995]} rotation={[-1.412, 1.412, -0.126]} scale={100} />
          <mesh geometry={nodes.Cube032_low_Parts_0.geometry} material={materials.Parts} position={[-46.956, 10.021, 12.256]} rotation={[-Math.PI / 2, 0.207, 0]} scale={100} />
          <mesh geometry={nodes.Plane002_low_Parts_0.geometry} material={materials.Parts} position={[-40.778, 18.767, -36.487]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Plane010_low_Parts_0.geometry} material={materials.Parts} position={[73.635, 5.648, -70.962]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cube002_low_Parts_0.geometry} material={materials.Parts} position={[88.493, 4.923, -8.084]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube036_low_Parts_0.geometry} material={materials.Parts} position={[46.046, 39.832, 11.49]} rotation={[-Math.PI / 2, 0.022, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/computer/computer1.gltf')
